
services:
  backend:
    build: ./api
    ports:
      - "5174:5174"
    environment:
      - DATABASE_URL=postgresql://karma:karma1234@172.31.6.95:5432/byte_reads    
    networks:
      - bossmode2_network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://3.147.55.38:5174
    depends_on:
      - backend
    networks:
      - bossmode2_network

 
  scraper:
    build: ./scraper
    environment:
      - DATABASE_URL=postgresql://karma:karma1234@172.31.6.95:5432/byte_reads
    networks:
      - bossmode2_network

networks:
  bossmode2_network:

volumes:
  pgdata:
