
services:
  backend:
    build: ./api
    ports:
      - "5174:5174"
    #volumes:
    #  - ./api:/app
    #  - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/project
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bossmode2_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    #volumes:
    #  - ./frontend:/app
    #  - /app/node_modules:/app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - bossmode2_network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bossmode2_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

networks:
  bossmode2_network:

volumes:
  pgdata:
