
services:
  backend:
    build: ./api
    ports:
      - "5174:5174"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    networks:
      - bossmode2_network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - bossmode2_network

 
  scraper:
    build: ./scraper
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - bossmode2_network

networks:
  bossmode2_network:

volumes:
  pgdata:
