name: Frontend CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-run"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      # Sets up Node.js and caching for pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'  
          cache-dependency-path: ./frontend/pnpm-lock.yaml  

      - name: Install api dependencies
        working-directory: ./api
        run: pnpm install

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      # Runs a set of commands using the runners shell
      - name: Build
        working-directory: ./frontend
        run: pnpm build
